# Load packages and libraries

In [1]:
.libPaths()
assign(".lib.loc", "/home/manuel.tardaguila/conda_envs/multiome_NEW_downstream_analysis/lib/R/library", envir = environment(.libPaths))
.libPaths()
# sessionInfo()


suppressMessages(library(dplyr)) 
suppressMessages(library(ggplot2)) 
suppressMessages(library(Matrix)) 
suppressMessages(library(data.table)) 
suppressMessages(library(ggpubr)) 
suppressMessages(library(ggplot2))
suppressMessages(library(pheatmap))
suppressMessages(library("cowplot"))
suppressMessages(library("RColorBrewer"))
suppressMessages(library("plyr"))
suppressMessages(library("forcats"))
suppressMessages(library('ggeasy'))
suppressMessages(library('dplyr'))
suppressMessages(library("svglite"))
suppressMessages(library("ape"))
suppressMessages(library("ggforce"))
suppressMessages(library("tidyr"))
suppressMessages(library("tibble")) 
library("ggrepel")

library("optparse")
suppressMessages(library("splitstackshape")) 
suppressMessages(library("ggupset"))

[1] "/group/soranzo/conda_envs/multiome_NEW_downstream_analysis/lib/R/library"

[1] "/home/manuel.tardaguila/conda_envs/multiome_NEW_downstream_analysis/lib/R/library"

# Read DE results

In [2]:
setwd("/group/soranzo/manuel.tardaguila/2025_K562_multiome_reanalysis/Downstream_analysis/DE_per_cluster/")

In [3]:
DE_results<-readRDS(file="DE_results_Diff_K562.rds")

cat("DE_results_0\n")
cat(str(DE_results))
cat("\n")

DE_results_0
'data.frame':	322320 obs. of  10 variables:
 $ gene          : chr  "PURPL" "GNB1" "RER1" "RPL22" ...
 $ baseMean      : num  9.2 5.98 6.08 11.84 32.94 ...
 $ log2FoldChange: num  8.62e-06 -2.07e-06 1.73e-06 -4.44e-06 -3.18e-06 ...
 $ lfcSE         : num  0.00144 0.00144 0.00144 0.00144 0.00144 ...
 $ pvalue        : num  9.88e-06 3.22e-01 4.99e-01 1.12e-01 2.55e-01 ...
 $ padj          : num  0.0159 0.9976 0.9976 0.9976 0.9976 ...
 $ contrast      : Ord.factor w/ 5 levels "Genotype_rs139141690_HET_vs_wt"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ identity      : Ord.factor w/ 13 levels "1"<"2"<"3"<"4"<..: 13 13 13 13 13 13 13 13 13 13 ...
 $ minuslog10padj: num  1.79762 0.00104 0.00104 0.00104 0.00104 ...
 $ abslogfc      : num  8.62e-06 2.07e-06 1.73e-06 4.44e-06 3.18e-06 ...

# Read ORA annotations

In [13]:
setwd("/group/soranzo/manuel.tardaguila/2025_K562_multiome_reanalysis/Downstream_analysis/DE_per_cluster/")

In [14]:
annotation_file<-read.table(file="genes_ORA_annotated_global_Diff_K562.tsv", sep="\t", header=T)

cat("annotation_file_0\n")
cat(str(annotation_file))
cat("\n")


annotation_file_gene_names<-annotation_file[-grep("^[0-9]+$",annotation_file$gene),]

annotation_file_long<-unique(as.data.frame(cSplit(annotation_file_gene_names,sep = '|', direction = "long",
                                                    splitCols = "other"),stringsAsFactors=F))
  
cat("annotation_file_long_0\n")
cat(str(annotation_file_long))
cat("\n")

annotation_file_0
'data.frame':	1798 obs. of  4 variables:
 $ gene      : chr  "10049" "10077" "10098" "10133" ...
 $ identity  : int  1 1 1 7 1 3 5 3 4 3 ...
 $ other     : chr  "TRAVAGLINI_LUNG_PLATELET_MEGAKARYOCYTE_CELL" "DESCARTES_FETAL_CEREBRUM_MEGAKARYOCYTES|DESCARTES_FETAL_HEART_MEGAKARYOCYTES|DESCARTES_FETAL_LUNG_MEGAKARYOCYTE"| __truncated__ "HE_LIM_SUN_FETAL_LUNG_C2_HSC_ELP_CELL|VALK_AML_CLUSTER_8" "HE_LIM_SUN_FETAL_LUNG_C2_PLATELET_CELL" ...
 $ TF_targets: chr  NA NA NA NA ...

Warning message in type.convert.default(unlist(x, use.names = FALSE)):
“'as.is' should be specified by the caller; using TRUE”

annotation_file_long_0
'data.frame':	5028 obs. of  4 variables:
 $ gene      : chr  "A2M" "A2M" "A2M" "A2M" ...
 $ identity  : int  3 3 3 3 3 3 3 3 3 7 ...
 $ other     : chr  "GOCC_PLATELET_ALPHA_GRANULE" "GOCC_PLATELET_ALPHA_GRANULE_LUMEN" "MANNE_COVID19_COMBINED_COHORT_VS_HEALTHY_DONOR_PLATELETS_DN" "MANNE_COVID19_ICU_VS_HEALTHY_DONOR_PLATELETS_DN" ...
 $ TF_targets: chr  NA NA NA NA ...

In [15]:
length(grep("^[0-9]+$",annotation_file$gene))

[1] 332

## Search for genes I need to include from the previous version of the manuscript

In [49]:
annotation_file$other[which(annotation_file$gene == 'MOCOS')]

[1] "AKT_UP.V1_DN|AKT_UP_MTOR_DN.V1_DN" "AKT_UP.V1_DN|AKT_UP_MTOR_DN.V1_DN"

In [52]:
annotation_file$other[which(annotation_file$gene == 'ITPR2')]

character(0)

# Selected annotations

In [112]:
#WP_PI3KAKT_SIGNALING

In [113]:
annotations<-c("GOBP_MEGAKARYOCYTE_DIFFERENTIATION","HP_ABNORMAL_PLATELET_VOLUME","HP_INCREASED_MEAN_PLATELET_VOLUME","AKT_UP_MTOR_DN.V1_UP","WP_PI3KAKT_SIGNALING") #"AKT_UP_MTOR_DN.V1_DN","CREIGHTON_AKT1_SIGNALING_VIA_MTOR_DN"

In [114]:
annotation_file_long_sel<-annotation_file_long[grep(paste(annotations, collapse="|"), annotation_file_long$other),]

cat("annotation_file_long_sel_0\n")
cat(str(annotation_file_long_sel))
cat("\n")
cat(str(unique(annotation_file_long_sel$gene)))
cat("\n")

cat(sprintf(as.character(unique(annotation_file_long_sel$gene))))
cat("\n")
cat("\n")

cat(sprintf(as.character(unique(annotation_file_long_sel$other))))
cat("\n")

annotation_file_long_sel_0
'data.frame':	86 obs. of  4 variables:
 $ gene      : chr  "ABI1" "ABI1" "ACTB" "ACTB" ...
 $ identity  : int  3 1 1 1 3 1 3 1 1 7 ...
 $ other     : chr  "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "HP_ABNORMAL_PLATELET_VOLUME" "HP_INCREASED_MEAN_PLATELET_VOLUME" ...
 $ TF_targets: chr  "GRN_RUNX1|PU1_Q6|RGAGGAARY_PU1_Q6" "GRN_RUNX1|PU1_Q6|RGAGGAARY_PU1_Q6" "Dorothea_ABCDE_CUX1_targets|Dorothea_ABCD_CUX1_targets" "Dorothea_ABCDE_CUX1_targets|Dorothea_ABCD_CUX1_targets" ...

 chr [1:52] "ABI1" "ACTB" "ADAM10" "ANGPT1" "ARRDC4" "ATF3" "BLVRB" ...

ABI1 ACTB ADAM10 ANGPT1 ARRDC4 ATF3 BLVRB C3orf52 CCND2 CD55 CIR1 CNOT4 COL6A5 CREB5 DHCR24 DIAPH1 FGF13 FLNA FYB1 GFI1B GSK3B GUSB HOXB3 HSP90AA1 HSP90AB1 HSP90B1 IL1R1 IL7 ITGA2B ITGAV KIT LAMA2 MEF2C MEIS1 MYB PIK3CA PIK3CG PIP4K2A PKN2 PLAGL1 PPP2R3A RBL2 SGPL1 SH2B3 SLC44A1 SLC6A6 SOS1 SUCO TOR3A TPM4 TUBB1 ZFPM1

GOBP_MEGAKARYOCYTE_DIFFERENTIATION HP_ABNORMAL_PLATELET_VOLUME HP_INCREASED_MEAN_PLATELET_VOLUME AKT_UP_MTOR_DN.V1_UP WP_PI3KAKT_SIGNALING

## collapse AKT/MTOR signatures

In [115]:
annotation_file_long_sel$other[which(annotation_file_long_sel$other%in%c("AKT_UP_MTOR_DN.V1_UP","AKT_UP_MTOR_DN.V1_DN","CREIGHTON_AKT1_SIGNALING_VIA_MTOR_DN"))]<-'AKT_MTOR_SIGNALING'

### collapse of overlapping genes

In [116]:
annotation_file_long_sel_for_collapse<-unique(annotation_file_long_sel[,which(colnames(annotation_file_long_sel)%in%c('gene','other'))])

annotation_file_long_sel_for_collapse<-annotation_file_long_sel_for_collapse[order(annotation_file_long_sel_for_collapse$gene, annotation_file_long_sel_for_collapse$other),]

cat("annotation_file_long_sel_for_collapse_0\n")
cat(str(annotation_file_long_sel_for_collapse))
cat("\n")

annotation_file_long_sel_for_collapse_0
'data.frame':	61 obs. of  2 variables:
 $ gene : chr  "ABI1" "ACTB" "ACTB" "ADAM10" ...
 $ other: chr  "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "HP_ABNORMAL_PLATELET_VOLUME" "HP_INCREASED_MEAN_PLATELET_VOLUME" "AKT_MTOR_SIGNALING" ...

In [117]:
annotation_file_long_sel_for_collapse.dt<-data.table(annotation_file_long_sel_for_collapse, key='gene')
      
annotation_file_sel_collapsed<-unique(as.data.frame(annotation_file_long_sel_for_collapse.dt[,.(other_string=paste(other, collapse="|")), by=key(annotation_file_long_sel_for_collapse.dt)], stringsAsFactors=F))



cat("annotation_file_sel_collapsed_0\n")
cat(str(annotation_file_sel_collapsed))
cat("\n")
cat(names(summary(as.factor(annotation_file_sel_collapsed$other_string))))
cat("\n")
cat(summary(as.factor(annotation_file_sel_collapsed$other_string)))
cat("\n")

annotation_file_sel_collapsed_0
'data.frame':	52 obs. of  2 variables:
 $ gene        : chr  "ABI1" "ACTB" "ADAM10" "ANGPT1" ...
 $ other_string: chr  "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME" "AKT_MTOR_SIGNALING" "WP_PI3KAKT_SIGNALING" ...

AKT_MTOR_SIGNALING GOBP_MEGAKARYOCYTE_DIFFERENTIATION GOBP_MEGAKARYOCYTE_DIFFERENTIATION|WP_PI3KAKT_SIGNALING HP_ABNORMAL_PLATELET_VOLUME HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME|WP_PI3KAKT_SIGNALING WP_PI3KAKT_SIGNALING
16 9 1 1 6 1 18

In [118]:
annotation_file_sel_collapsed$gene[grep("IL", annotation_file_sel_collapsed$gene)]

[1] "IL1R1" "IL7"

# Read in ORA result

In [119]:
ORA_result<-readRDS(file="/group/soranzo/manuel.tardaguila/2025_K562_multiome_reanalysis/Downstream_analysis/DE_per_cluster/ORA_global_results_significant_Diff_K562.rds")

ORA_result<-droplevels(ORA_result)

summary(ORA_result$contrast)


cat("ORA_result_0\n")
str(ORA_result)
cat("\n")

       Genotype_Del_80bp_vs_wt        Genotype_Del_16bp_vs_wt
                           834                            464
    Genotype_rs139141690_vs_wt Genotype_rs139141690_HET_vs_wt
                           577                             61

ORA_result_0
'data.frame':	1936 obs. of  15 variables:
 $ ID            : chr  "GSE15330_HSC_VS_MEGAKARYOCYTE_ERYTHROID_PROGENITOR_IKAROS_KO_DN" "GSE15330_LYMPHOID_MULTIPOTENT_VS_MEGAKARYOCYTE_ERYTHROID_PROGENITOR_UP" "GSE26290_CTRL_VS_AKT_INHIBITOR_TREATED_ANTI_CD3_AND_IL2_STIM_CD8_TCELL_DN" "RACCACAR_AML_Q6" ...
 $ Description   : chr  "GSE15330_HSC_VS_MEGAKARYOCYTE_ERYTHROID_PROGENITOR_IKAROS_KO_DN" "GSE15330_LYMPHOID_MULTIPOTENT_VS_MEGAKARYOCYTE_ERYTHROID_PROGENITOR_UP" "GSE26290_CTRL_VS_AKT_INHIBITOR_TREATED_ANTI_CD3_AND_IL2_STIM_CD8_TCELL_DN" "RACCACAR_AML_Q6" ...
 $ GeneRatio     : chr  "1/1" "1/1" "1/1" "1/1" ...
 $ BgRatio       : chr  "116/9747" "154/9747" "131/9747" "151/9747" ...
 $ RichFactor    : num  0.00862 0.00649 0.00763 0.00662 0.04348 ...
 $ FoldEnrichment: num  84 63.3 74.4 64.5 423.8 ...
 $ zScore        : num  9.11 7.89 8.57 7.97 20.56 ...
 $ pvalue        : num  0.0119 0.0158 0.01344 0.01549 0.00236 ...
 $ p.adjust      : num  0.0158 0.0158 0.0158 0.01549 0.00236 ...
 $ qvalue        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ Count         : int  1 1 1 1 1 1 1 1 1 1 ...
 $ minuslog10padj: num  1.8 1.8 1.8 1.81 2.63 ...
 $ geneID        : chr  "TBL1X" "TBL1X" "TBL1X" "TBL1X" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_Del_80bp_vs_wt"<..: 1 1 1 1 1 1 3 3 3 3 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 1 1 1 1 1 1 1 1 1 1 ...

In [120]:
HET<-ORA_result[which(ORA_result$contrast == 'Genotype_rs139141690_HET_vs_wt'),]


cat("HET_0\n")
str(HET)
cat("\n")


HET[grep("AKT",HET$ID),]

HET_0
'data.frame':	61 obs. of  15 variables:
 $ ID            : chr  "GSE23502_BM_VS_COLON_TUMOR_HDC_KO_MYELOID_DERIVED_SUPPRESSOR_CELL_DN" "NAKAYA_MYELOID_DENDRITIC_CELL_FLUMIST_AGE_18_50YO_7DY_UP" "Dorothea_ABC_FOXP1_targets" "Dorothea_AB_FOXP1_targets" ...
 $ Description   : chr  "GSE23502_BM_VS_COLON_TUMOR_HDC_KO_MYELOID_DERIVED_SUPPRESSOR_CELL_DN" "NAKAYA_MYELOID_DENDRITIC_CELL_FLUMIST_AGE_18_50YO_7DY_UP" "Dorothea_ABC_FOXP1_targets" "Dorothea_AB_FOXP1_targets" ...
 $ GeneRatio     : chr  "1/1" "1/1" "2/2" "2/2" ...
 $ BgRatio       : chr  "156/9747" "301/9747" "272/9747" "131/9747" ...
 $ RichFactor    : num  0.00641 0.00332 0.00735 0.01527 0.02941 ...
 $ FoldEnrichment: num  62.5 32.4 35.8 74.4 47.8 ...
 $ zScore        : num  7.84 5.6 8.35 12.12 6.78 ...
 $ pvalue        : num  0.016005 0.030881 0.000776 0.000179 0.020753 ...
 $ p.adjust      : num  0.030881 0.030881 0.001552 0.000359 0.041506 ...
 $ qvalue        : num  NA NA 0.000817 0.000189 0.021845 ...
 $ Count         : int  1 1 2 2 1 1 1 2 1 1 ...
 $ minuslog10padj: num  1.51 1.51 2.81 3.45 1.38 ...
 $ geneID        : chr  "EHBP1" "EHBP1" "HIVEP2/ROCK1" "HIVEP2/ROCK1" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_Del_80bp_vs_wt"<..: 4 4 4 4 4 4 4 4 4 4 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 3 3 10 10 10 10 10 10 10 10 ...

      ID                                   Description
11015 AKT_UP.V1_DN                         AKT_UP.V1_DN
2710  AKT_UP_MTOR_DN.V1_DN                 AKT_UP_MTOR_DN.V1_DN
5221  AKT_UP.V1_DN                         AKT_UP.V1_DN
5321  AKT_UP_MTOR_DN.V1_DN                 AKT_UP_MTOR_DN.V1_DN
9711  CREIGHTON_AKT1_SIGNALING_VIA_MTOR_DN CREIGHTON_AKT1_SIGNALING_VIA_MTOR_DN
      GeneRatio BgRatio RichFactor FoldEnrichment zScore    pvalue
11015 1/1       86/9747 0.01162791 113.33721      10.598925 0.0088232277
2710  1/1       95/9747 0.01052632 102.60000      10.079683 0.0097465887
5221  1/1       86/9747 0.01162791 113.33721      10.598925 0.0088232277
5321  1/1       95/9747 0.01052632 102.60000      10.079683 0.0097465887
9711  2/19      21/9747 0.09523810  48.85714       9.702139 0.0007395234
      p.adjust    qvalue      Count minuslog10padj geneID
11015 0.009746589          NA 1     2.011147       MOCOS
2710  0.009746589          NA 1     2.011147       MOCOS
5221  0.009746589          NA 1     2.011147       MOCOS
5321  0.009746589          NA 1     2.011147       MOCOS
9711  0.013609741 0.009252236 2     1.866150       GPI/ATP6V0B
      contrast                       identity
11015 Genotype_rs139141690_HET_vs_wt 4
2710  Genotype_rs139141690_HET_vs_wt 4
5221  Genotype_rs139141690_HET_vs_wt 1
5321  Genotype_rs139141690_HET_vs_wt 1
9711  Genotype_rs139141690_HET_vs_wt 1

## Selected annotations

In [121]:
ORA_result_sel<-ORA_result[which(ORA_result$ID%in%c(annotations) &
                                ORA_result$identity %in%c('1','3')),]

cat("ORA_result_sel_0\n")
str(ORA_result_sel)
cat("\n")

summary(as.factor(ORA_result_sel$ID))
cat("\n")

ORA_result_sel.dt<-data.table(ORA_result_sel, keys=c('ID','contrast','identity'))

ORA_result_sel_max<-as.data.frame(ORA_result_sel.dt[,.SD[which.max(Count)], by=c('ID','contrast','identity')], stringsAsFactors=F)

cat("ORA_result_sel_max_0\n")
str(ORA_result_sel_max)
cat("\n")

ORA_result_sel_0
'data.frame':	28 obs. of  15 variables:
 $ ID            : chr  "AKT_UP_MTOR_DN.V1_UP" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "WP_PI3KAKT_SIGNALING" "AKT_UP_MTOR_DN.V1_UP" ...
 $ Description   : chr  "AKT_UP_MTOR_DN.V1_UP" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "WP_PI3KAKT_SIGNALING" "AKT_UP_MTOR_DN.V1_UP" ...
 $ GeneRatio     : chr  "3/4" "4/51" "11/146" "2/9" ...
 $ BgRatio       : chr  "99/9747" "41/9747" "176/9747" "99/9747" ...
 $ RichFactor    : num  0.0303 0.0976 0.0625 0.0202 0.2381 ...
 $ FoldEnrichment: num  73.84 18.65 4.17 21.88 74.86 ...
 $ zScore        : num  14.76 8.21 5.24 6.35 19.14 ...
 $ pvalue        : num  4.04e-06 5.84e-05 6.45e-05 3.51e-03 4.56e-09 ...
 $ p.adjust      : num  8.07e-06 5.45e-04 2.00e-03 3.51e-03 1.18e-08 ...
 $ qvalue        : num  NA 2.33e-04 1.25e-03 NA 9.59e-10 ...
 $ Count         : int  3 4 11 2 5 4 4 5 4 2 ...
 $ minuslog10padj: num  5.09 3.26 2.7 2.45 7.93 ...
 $ geneID        : chr  "ADAM10/IL1R1/TOR3A" "PIP4K2A/MEF2C/BLVRB/MEIS1" "PKN2/PPP2R3A/ANGPT1/HSP90AA1/PIK3CG/HSP90AB1/PIK3CA/LAMA2/CCND2/SOS1/RBL2" "TOR3A/SUCO" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_Del_80bp_vs_wt"<..: 2 2 2 1 1 1 1 1 1 3 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 11 11 11 11 11 11 11 11 11 11 ...

              AKT_UP_MTOR_DN.V1_UP GOBP_MEGAKARYOCYTE_DIFFERENTIATION
                                 4                                  5
       HP_ABNORMAL_PLATELET_VOLUME  HP_INCREASED_MEAN_PLATELET_VOLUME
                                 8                                  7
              WP_PI3KAKT_SIGNALING
                                 4

Warning message in as.data.table.list(x, keep.rownames = keep.rownames, check.names = check.names, :
“Item 2 has 3 rows but longest item has 28; recycled with remainder.”

ORA_result_sel_max_0
'data.frame':	21 obs. of  16 variables:
 $ ID            : chr  "AKT_UP_MTOR_DN.V1_UP" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "WP_PI3KAKT_SIGNALING" "AKT_UP_MTOR_DN.V1_UP" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_Del_80bp_vs_wt"<..: 2 2 2 1 1 1 1 3 3 3 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 11 11 11 11 11 11 11 11 11 11 ...
 $ Description   : chr  "AKT_UP_MTOR_DN.V1_UP" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "WP_PI3KAKT_SIGNALING" "AKT_UP_MTOR_DN.V1_UP" ...
 $ GeneRatio     : chr  "3/4" "4/51" "11/146" "2/9" ...
 $ BgRatio       : chr  "99/9747" "41/9747" "176/9747" "99/9747" ...
 $ RichFactor    : num  0.0303 0.0976 0.0625 0.0202 0.2381 ...
 $ FoldEnrichment: num  73.84 18.65 4.17 21.88 74.86 ...
 $ zScore        : num  14.76 8.21 5.24 6.35 19.14 ...
 $ pvalue        : num  4.04e-06 5.84e-05 6.45e-05 3.51e-03 4.56e-09 ...
 $ p.adjust      : num  8.07e-06 5.45e-04 2.00e-03 3.51e-03 1.18e-08 ...
 $ qvalue        : num  NA 2.33e-04 1.25e-03 NA 9.59e-10 ...
 $ Count         : int  3 4 11 2 5 4 4 2 1 4 ...
 $ minuslog10padj: num  5.09 3.26 2.7 2.45 7.93 ...
 $ geneID        : chr  "ADAM10/IL1R1/TOR3A" "PIP4K2A/MEF2C/BLVRB/MEIS1" "PKN2/PPP2R3A/ANGPT1/HSP90AA1/PIK3CG/HSP90AB1/PIK3CA/LAMA2/CCND2/SOS1/RBL2" "TOR3A/SUCO" ...
 $ keys          : chr  "ID" "contrast" "identity" "ID" ...

In [122]:
ORA_result_sel_max_custom_tiebreak <- ORA_result_sel.dt[
  order(-Count, -minuslog10padj), # Sort by Count descending, then Other_Col descending
  .SD[1],                    # Take the first row after sorting within the group
  by=c('ID','contrast','identity')
]

cat("ORA_result_sel_max_custom_tiebreak_0\n")
str(ORA_result_sel_max_custom_tiebreak)
cat("\n")


ORA_result_sel_max_custom_tiebreak[which(ORA_result_sel_max_custom_tiebreak$contrast == 'Genotype_rs139141690_vs_wt'),]

ORA_result_sel_max_custom_tiebreak_0
Classes ‘data.table’ and 'data.frame':	21 obs. of  16 variables:
 $ ID            : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_Del_80bp_vs_wt"<..: 3 2 1 3 1 3 1 1 1 3 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 11 11 13 13 11 13 13 11 13 11 ...
 $ Description   : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ GeneRatio     : chr  "11/147" "11/146" "10/211" "7/129" ...
 $ BgRatio       : chr  "176/9747" "176/9747" "176/9747" "176/9747" ...
 $ RichFactor    : num  0.0625 0.0625 0.0568 0.0398 0.2381 ...
 $ FoldEnrichment: num  4.14 4.17 2.62 3.01 74.86 ...
 $ zScore        : num  5.21 5.24 3.24 3.11 19.14 ...
 $ pvalue        : num  6.87e-05 6.45e-05 4.89e-03 8.78e-03 4.56e-09 ...
 $ p.adjust      : num  1.56e-03 2.00e-03 1.79e-02 3.88e-02 1.18e-08 ...
 $ qvalue        : num  1.03e-03 1.25e-03 8.98e-03 2.73e-02 9.59e-10 ...
 $ Count         : int  11 11 10 7 5 5 5 4 4 4 ...
 $ minuslog10padj: num  2.81 2.7 1.75 1.41 7.93 ...
 $ geneID        : chr  "6009/4602/7184/5155/3914/3674/3480/3320/1950/5525/5154" "PKN2/PPP2R3A/ANGPT1/HSP90AA1/PIK3CG/HSP90AB1/PIK3CA/LAMA2/CCND2/SOS1/RBL2" "ITGA2B/GSK3B/FGF13/ITGAV/COL6A5/ANGPT1/IL7/KIT/CREB5/HSP90B1" "6009/5154/118788/3685/5155/284/2247" ...
 $ keys          : chr  "contrast" "identity" "ID" "ID" ...
 - attr(*, ".internal.selfref")=<externalptr>

  ID                                 contrast                   identity
1 WP_PI3KAKT_SIGNALING               Genotype_rs139141690_vs_wt 3
2 WP_PI3KAKT_SIGNALING               Genotype_rs139141690_vs_wt 1
3 AKT_UP_MTOR_DN.V1_UP               Genotype_rs139141690_vs_wt 1
4 GOBP_MEGAKARYOCYTE_DIFFERENTIATION Genotype_rs139141690_vs_wt 3
5 GOBP_MEGAKARYOCYTE_DIFFERENTIATION Genotype_rs139141690_vs_wt 1
6 HP_ABNORMAL_PLATELET_VOLUME        Genotype_rs139141690_vs_wt 3
7 HP_INCREASED_MEAN_PLATELET_VOLUME  Genotype_rs139141690_vs_wt 3
  Description                        GeneRatio BgRatio  RichFactor
1 WP_PI3KAKT_SIGNALING               11/147    176/9747 0.06250000
2 WP_PI3KAKT_SIGNALING               7/129     176/9747 0.03977273
3 AKT_UP_MTOR_DN.V1_UP               5/14      99/9747  0.05050505
4 GOBP_MEGAKARYOCYTE_DIFFERENTIATION 4/56      41/9747  0.09756098
5 GOBP_MEGAKARYOCYTE_DIFFERENTIATION 3/52      41/9747  0.07317073
6 HP_ABNORMAL_PLATELET_VOLUME        2/17      21/9747  0.09523810
7 HP_INCREASED_MEAN_PLATELET_VOLUME  1/17      16/9747  0.06250000
  FoldEnrichment zScore    pvalue       p.adjust     qvalue       Count
1  4.144133       5.208525 6.868948e-05 1.562448e-03 0.0010279265 11
2  3.005153       3.108787 8.777661e-03 3.883693e-02 0.0272539827  7
3 35.162338      12.956879 1.818216e-07 1.818216e-07           NA  5
4 16.980836       7.794607 8.449808e-05 4.295319e-04 0.0001260059  4
5 13.715291       5.975016 1.323312e-03 5.482294e-03 0.0026864234  3
6 54.605042      10.278492 5.896888e-04 1.179378e-03           NA  2
7 35.834559       5.828715 2.756488e-02 2.756488e-02           NA  1
  minuslog10padj geneID
1 2.806194       6009/4602/7184/5155/3914/3674/3480/3320/1950/5525/5154
2 1.410755       6009/5154/118788/3685/5155/284/2247
3 6.740355       GUSB/ARRDC4/SLC6A6/CIR1/DHCR24
4 3.367005       MEIS1/MYB/PIP4K2A/CNOT4
5 2.261038       MEIS1/PIP4K2A/CNOT4
6 2.928347       FYB1/ITGA2B
7 1.559644       ITGA2B
  keys
1 contrast
2 ID
3 contrast
4 identity
5 identity
6 ID
7 contrast

In [123]:
summary(ORA_result_sel_max_custom_tiebreak$contrast)

       Genotype_Del_80bp_vs_wt        Genotype_Del_16bp_vs_wt
                             9                              5
    Genotype_rs139141690_vs_wt Genotype_rs139141690_HET_vs_wt
                             7                              0

## Reorder levels

In [124]:
new_order<-rev(levels(ORA_result_sel_max_custom_tiebreak$contrast))

new_order


ORA_result_sel_max_custom_tiebreak$contrast<-factor(ORA_result_sel_max_custom_tiebreak$contrast,
                               levels=new_order,
                               ordered=T)

cat("ORA_result_sel_max_custom_tiebreak_0\n")
str(ORA_result_sel_max_custom_tiebreak)
cat("\n")

[1] "Genotype_rs139141690_HET_vs_wt" "Genotype_rs139141690_vs_wt"
[3] "Genotype_Del_16bp_vs_wt"        "Genotype_Del_80bp_vs_wt"

ORA_result_sel_max_custom_tiebreak_0
Classes ‘data.table’ and 'data.frame':	21 obs. of  16 variables:
 $ ID            : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_rs139141690_HET_vs_wt"<..: 2 3 4 2 4 2 4 4 4 2 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 11 11 13 13 11 13 13 11 13 11 ...
 $ Description   : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ GeneRatio     : chr  "11/147" "11/146" "10/211" "7/129" ...
 $ BgRatio       : chr  "176/9747" "176/9747" "176/9747" "176/9747" ...
 $ RichFactor    : num  0.0625 0.0625 0.0568 0.0398 0.2381 ...
 $ FoldEnrichment: num  4.14 4.17 2.62 3.01 74.86 ...
 $ zScore        : num  5.21 5.24 3.24 3.11 19.14 ...
 $ pvalue        : num  6.87e-05 6.45e-05 4.89e-03 8.78e-03 4.56e-09 ...
 $ p.adjust      : num  1.56e-03 2.00e-03 1.79e-02 3.88e-02 1.18e-08 ...
 $ qvalue        : num  1.03e-03 1.25e-03 8.98e-03 2.73e-02 9.59e-10 ...
 $ Count         : int  11 11 10 7 5 5 5 4 4 4 ...
 $ minuslog10padj: num  2.81 2.7 1.75 1.41 7.93 ...
 $ geneID        : chr  "6009/4602/7184/5155/3914/3674/3480/3320/1950/5525/5154" "PKN2/PPP2R3A/ANGPT1/HSP90AA1/PIK3CG/HSP90AB1/PIK3CA/LAMA2/CCND2/SOS1/RBL2" "ITGA2B/GSK3B/FGF13/ITGAV/COL6A5/ANGPT1/IL7/KIT/CREB5/HSP90B1" "6009/5154/118788/3685/5155/284/2247" ...
 $ keys          : chr  "contrast" "identity" "ID" "ID" ...
 - attr(*, ".internal.selfref")=<externalptr>

# Selected genes

In [126]:
genes<-c("CUX1","RUNX1","EZH2","XRCC2","TBXAS1","TBXA2R","MOCOS","GPI","ATP6V0B")

annotation_of_selected_genes<-c("CUX1","RUNX1",rep("EZH2 and targets",2),rep("Thromboxane metabolism",2),rep("AKT_MTOR_SIGNALING",3))


selected_genes_df<-as.data.frame(cbind(genes,annotation_of_selected_genes))

colnames(selected_genes_df)<-c("gene","other_string")

cat("selected_genes_df_0\n")
cat(str(selected_genes_df))
cat("\n")

selected_genes_df_0
'data.frame':	9 obs. of  2 variables:
 $ gene        : chr  "CUX1" "RUNX1" "EZH2" "XRCC2" ...
 $ other_string: chr  "CUX1" "RUNX1" "EZH2 and targets" "EZH2 and targets" ...

# Put together and select from DE genes

In [127]:
REP_genes<-rbind(selected_genes_df,annotation_file_sel_collapsed)

cat("REP_genes_0\n")
cat(str(REP_genes))
cat("\n")
cat(str(unique(REP_genes$gene)))
cat("\n")

REP_genes_0
'data.frame':	61 obs. of  2 variables:
 $ gene        : chr  "CUX1" "RUNX1" "EZH2" "XRCC2" ...
 $ other_string: chr  "CUX1" "RUNX1" "EZH2 and targets" "EZH2 and targets" ...

 chr [1:61] "CUX1" "RUNX1" "EZH2" "XRCC2" "TBXAS1" "TBXA2R" "MOCOS" "GPI" ...

In [128]:
str(REP_genes)

'data.frame':	61 obs. of  2 variables:
 $ gene        : chr  "CUX1" "RUNX1" "EZH2" "XRCC2" ...
 $ other_string: chr  "CUX1" "RUNX1" "EZH2 and targets" "EZH2 and targets" ...

In [129]:
names(summary(as.factor(REP_genes$other_string)))

 [1] "AKT_MTOR_SIGNALING"
 [2] "CUX1"
 [3] "EZH2 and targets"
 [4] "GOBP_MEGAKARYOCYTE_DIFFERENTIATION"
 [5] "GOBP_MEGAKARYOCYTE_DIFFERENTIATION|WP_PI3KAKT_SIGNALING"
 [6] "HP_ABNORMAL_PLATELET_VOLUME"
 [7] "HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME"
 [8] "HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME|WP_PI3KAKT_SIGNALING"
 [9] "RUNX1"
[10] "Thromboxane metabolism"
[11] "WP_PI3KAKT_SIGNALING"

## simplify some classes

In [144]:
REP_genes$Gene_class<-REP_genes$other_string

In [145]:
REP_genes$Gene_class[which(REP_genes$Gene_class == 'HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME|WP_PI3KAKT_SIGNALING')]<-'HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME'
REP_genes$Gene_class[which(REP_genes$Gene_class == 'GOBP_MEGAKARYOCYTE_DIFFERENTIATION|WP_PI3KAKT_SIGNALING')]<-'GOBP_MEGAKARYOCYTE_DIFFERENTIATION'

In [146]:
names(summary(as.factor(REP_genes$Gene_class)))

[1] "AKT_MTOR_SIGNALING"
[2] "CUX1"
[3] "EZH2 and targets"
[4] "GOBP_MEGAKARYOCYTE_DIFFERENTIATION"
[5] "HP_ABNORMAL_PLATELET_VOLUME"
[6] "HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME"
[7] "RUNX1"
[8] "Thromboxane metabolism"
[9] "WP_PI3KAKT_SIGNALING"

In [147]:
REP_genes$Gene_class<-factor(REP_genes$Gene_class,
                            levels=c('CUX1',
                            'RUNX1',
                            'EZH2 and targets',
                            'GOBP_MEGAKARYOCYTE_DIFFERENTIATION',
                            'Thromboxane metabolism',
                            'HP_ABNORMAL_PLATELET_VOLUME',
                            'HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME',
                            'WP_PI3KAKT_SIGNALING',
                            'AKT_MTOR_SIGNALING'),
                            ordered=T)

In [168]:
str(REP_genes)
cat("\n")

summary(REP_genes$Gene_class)

'data.frame':	61 obs. of  3 variables:
 $ gene        : chr  "CUX1" "RUNX1" "EZH2" "XRCC2" ...
 $ other_string: chr  "CUX1" "RUNX1" "EZH2 and targets" "EZH2 and targets" ...
 $ Gene_class  : Ord.factor w/ 9 levels "CUX1"<"RUNX1"<..: 1 2 3 3 5 5 9 9 9 4 ...

                                                         CUX1
                                                            1
                                                        RUNX1
                                                            1
                                             EZH2 and targets
                                                            2
                           GOBP_MEGAKARYOCYTE_DIFFERENTIATION
                                                           10
                                       Thromboxane metabolism
                                                            2
                                  HP_ABNORMAL_PLATELET_VOLUME
                                                            1
HP_ABNORMAL_PLATELET_VOLUME|HP_INCREASED_MEAN_PLATELET_VOLUME
                                                            7
                                         WP_PI3KAKT_SIGNALING
                                                           18
                                           AKT_MTOR_SIGNALING
                                                           19

## SAVE REP genes

In [170]:
setwd("/group/soranzo/manuel.tardaguila/2025_K562_multiome_reanalysis/Downstream_analysis/DE_per_cluster/")

In [171]:
saveRDS(REP_genes,file="genes_from_tile_plot.rds")

# continue

In [149]:
DE_results_sel<-DE_results[which(DE_results$gene%in%REP_genes$gene &
                                DE_results$identity%in%c('3','1')),]

cat("DE_results_sel_0\n")
cat(str(DE_results_sel))
cat("\n")
cat(str(unique(DE_results_sel$gene)))
cat("\n")

DE_results_sel_0
'data.frame':	480 obs. of  10 variables:
 $ gene          : chr  "TBXAS1" "PIP4K2A" "HSP90AA1" "HSP90AB1" ...
 $ baseMean      : num  103.8 301.1 480.9 806.5 6.6 ...
 $ log2FoldChange: num  0.31914 0.21776 -0.01094 -0.01039 0.00297 ...
 $ lfcSE         : num  0.2083 0.1375 0.0247 0.0243 0.0209 ...
 $ pvalue        : num  0.00261 0.00255 0.00859 0.01222 0.01433 ...
 $ padj          : num  0.758 0.758 0.813 0.835 0.867 ...
 $ contrast      : Ord.factor w/ 5 levels "Genotype_rs139141690_HET_vs_wt"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ identity      : Ord.factor w/ 13 levels "1"<"2"<"3"<"4"<..: 3 3 3 3 3 3 3 3 3 3 ...
 $ minuslog10padj: num  0.1203 0.1203 0.09 0.0784 0.0618 ...
 $ abslogfc      : num  0.31914 0.21776 0.01094 0.01039 0.00297 ...

 chr [1:61] "TBXAS1" "PIP4K2A" "HSP90AA1" "HSP90AB1" "C3orf52" "MEF2C" ...

# path to graph

In [150]:
 path_graphs = paste("/group/soranzo/manuel.tardaguila/2025_K562_multiome_reanalysis/Downstream_analysis/Figure_graphs/",'/',sep='')
  
  if (file.exists(path_graphs)){
    
    
  }else{
    
    dir.create(file.path(path_graphs))
    
  }#path_Downstream_analysis

NULL

# Tile plot

In [151]:
DEBUG<-1

order_from_REP<-REP_genes$gene
        
        
cat("order_from_REP_0\n")
cat(str(order_from_REP))
cat("\n")



tile_plot<-DE_results_sel[which(DE_results_sel$gene%in%order_from_REP),]


if(DEBUG == 1){
  cat("tile_plot_0\n")
  cat(str(tile_plot))
  cat("\n")
}

tile_plot$gene<-factor(tile_plot$gene, levels=rev(order_from_REP), ordered=T)



tile_plot$SIG<-NA

tile_plot$SIG[which(tile_plot$minuslog10padj >= 1.3)]<-'YES'
tile_plot$SIG[which(tile_plot$minuslog10padj < 1.3)]<-'NO'


tile_plot$SIG<-factor(tile_plot$SIG, levels=c('NO','YES'), ordered=T)

if(DEBUG == 1){
  cat("tile_plot_1\n")
  cat(str(tile_plot))
  cat("\n")
}

order_from_REP_0
 chr [1:61] "CUX1" "RUNX1" "EZH2" "XRCC2" "TBXAS1" "TBXA2R" "MOCOS" "GPI" ...

tile_plot_0
'data.frame':	480 obs. of  10 variables:
 $ gene          : chr  "TBXAS1" "PIP4K2A" "HSP90AA1" "HSP90AB1" ...
 $ baseMean      : num  103.8 301.1 480.9 806.5 6.6 ...
 $ log2FoldChange: num  0.31914 0.21776 -0.01094 -0.01039 0.00297 ...
 $ lfcSE         : num  0.2083 0.1375 0.0247 0.0243 0.0209 ...
 $ pvalue        : num  0.00261 0.00255 0.00859 0.01222 0.01433 ...
 $ padj          : num  0.758 0.758 0.813 0.835 0.867 ...
 $ contrast      : Ord.factor w/ 5 levels "Genotype_rs139141690_HET_vs_wt"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ identity      : Ord.factor w/ 13 levels "1"<"2"<"3"<"4"<..: 3 3 3 3 3 3 3 3 3 3 ...
 $ minuslog10padj: num  0.1203 0.1203 0.09 0.0784 0.0618 ...
 $ abslogfc      : num  0.31914 0.21776 0.01094 0.01039 0.00297 ...

tile_plot_1
'data.frame':	480 obs. of  11 variables:
 $ gene          : Ord.factor w/ 61 levels "ZFPM1"<"TUBB1"<..: 57 15 29 28 45 20 27 53 38 14 ...
 $ baseMean      : num  103.8 301.1 480.9 806.5 6.6 ...
 $ log2FoldChange: num  0.31914 0.21776 -0.01094 -0.01039 0.00297 ...
 $ lfcSE         : num  0.2083 0.1375 0.0247 0.0243 0.0209 ...
 $ pvalue        : num  0.00261 0.00255 0.00859 0.01222 0.01433 ...
 $ padj          : num  0.758 0.758 0.813 0.835 0.867 ...
 $ contrast      : Ord.factor w/ 5 levels "Genotype_rs139141690_HET_vs_wt"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ identity      : Ord.factor w/ 13 levels "1"<"2"<"3"<"4"<..: 3 3 3 3 3 3 3 3 3 3 ...
 $ minuslog10padj: num  0.1203 0.1203 0.09 0.0784 0.0618 ...
 $ abslogfc      : num  0.31914 0.21776 0.01094 0.01039 0.00297 ...
 $ SIG           : Ord.factor w/ 2 levels "NO"<"YES": 1 1 1 1 1 1 1 1 1 1 ...

## Add the gene class information

In [152]:
tile_plot<-merge(tile_plot,
                 REP_genes,
                 by="gene")

if(DEBUG == 1){
  cat("tile_plot_2\n")
  cat(str(tile_plot))
  cat("\n")
}

tile_plot_2
'data.frame':	480 obs. of  13 variables:
 $ gene          : Ord.factor w/ 61 levels "ZFPM1"<"TUBB1"<..: 52 52 52 52 52 52 52 52 51 51 ...
 $ baseMean      : num  152 151 151 151 152 ...
 $ log2FoldChange: num  0.255711 0.156426 0.000448 0.168392 -0.006721 ...
 $ lfcSE         : num  0.0792 0.0786 0.0202 0.0998 0.0388 ...
 $ pvalue        : num  8.21e-05 8.88e-03 9.11e-01 2.44e-02 7.65e-01 ...
 $ padj          : num  0.0288 0.1365 0.9963 0.2421 0.975 ...
 $ contrast      : Ord.factor w/ 5 levels "Genotype_rs139141690_HET_vs_wt"<..: 3 2 1 3 1 4 4 2 1 4 ...
 $ identity      : Ord.factor w/ 13 levels "1"<"2"<"3"<"4"<..: 1 3 3 3 1 3 1 1 3 3 ...
 $ minuslog10padj: num  1.5411 0.8649 0.0016 0.6161 0.011 ...
 $ abslogfc      : num  0.255711 0.156426 0.000448 0.168392 0.006721 ...
 $ SIG           : Ord.factor w/ 2 levels "NO"<"YES": 2 1 1 1 1 2 2 1 1 1 ...
 $ other_string  : chr  "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" ...
 $ Gene_class    : Ord.factor w/ 9 levels "CUX1"<"RUNX1"<..: 4 4 4 4 4 4 4 4 7 7 ...

## graph

In [172]:
 ggheatmap_DE <-ggplot(data=tile_plot,
                     aes(x=contrast, y=gene, fill = log2FoldChange))+
    geom_tile()+
    geom_tile(data=subset(tile_plot, SIG == 'NO'), fill = NA, color = "black", linewidth = 0.1)+
    geom_tile(data=subset(tile_plot, SIG == 'YES'), fill = NA, color = "black", linewidth = 1)+
    scale_fill_gradient2(name=paste("log2FC", sep="\n"),
                         low = "blue", high = "red",mid="white",midpoint=0,
                         na.value = NA)

ggheatmap_DE<-ggheatmap_DE+
                     theme_cowplot(font_size = 2,
                  font_family = "sans")+
                     facet_grid(Gene_class ~ identity ,
             scales='free_y', space='free_y', switch="y",
             labeller = labeller(Gene_class = function(labels) paste("Gene Class:", labels))) + # Add a label for the Gene_class facet
                    theme( strip.background = element_blank(),
                           strip.placement = "outside",
                           strip.text = element_text(size=5,color="black", family="sans"),
                           panel.spacing = unit(0.2, "lines"),
                           panel.background=element_rect(fill="white"),
                           panel.border=element_rect(colour="white",size=0,5),
                           panel.grid.major = element_blank(),
                           panel.grid.minor = element_blank())+
            theme_classic()+
           theme(axis.title.y=element_blank(),
                 axis.title.x=element_blank(),
                 axis.text.y=element_text(size=8, color="black", family="sans"),
                 axis.text.x=element_text(angle=45,size=8,vjust=1, hjust=1, color="black", family="sans"),
                 axis.line.x = element_line(size = 0.4),
                 axis.ticks.x = element_blank(),
                 axis.ticks.y = element_line(size = 0.4),
                 axis.line.y = element_line(size = 0.4))+
           theme(legend.title = element_text(size=12),
                 legend.text = element_text(size=8),
                 legend.key.size = unit(0.5, 'cm'), #change legend key size
                 legend.key.height = unit(0.5, 'cm'), #change legend key height
                 legend.key.width = unit(0.5, 'cm'), #change legend key width
                 legend.position="right")+
           ggeasy::easy_center_title()

In [173]:
setwd(path_graphs)

svgname<-paste("Figure_5_panel_D_DE_part",".svg",sep='')

ggsave(svgname,plot=ggheatmap_DE, device ='svg',height=8, width = 3)

# Lolliplot of ORA pathways

In [159]:
#ORA_result_sel_max_custom_tiebreak

## graph

In [160]:
levels_ID<-unique(as.character(ORA_result_sel_max_custom_tiebreak$ID))
      
ORA_result_sel_max_custom_tiebreak$DUMMY<-factor(ORA_result_sel_max_custom_tiebreak$ID, 
                             levels=rev(annotations), ordered=T)

if(DEBUG ==1){

cat("ORA_result_sel_max_custom_tiebreak_1\n")
str(ORA_result_sel_max_custom_tiebreak)
cat("\n")
}

ORA_result_sel_max_custom_tiebreak$identity<-droplevels(factor(ORA_result_sel_max_custom_tiebreak$identity,
                          levels=c('1','3'),
                          ordered=TRUE))

if(DEBUG ==1){

cat("ORA_result_sel_max_custom_tiebreak_2\n")
str(ORA_result_sel_max_custom_tiebreak)
cat("\n")
}

ORA_result_sel_max_custom_tiebreak_1
Classes ‘data.table’ and 'data.frame':	21 obs. of  17 variables:
 $ ID            : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_rs139141690_HET_vs_wt"<..: 2 3 4 2 4 2 4 4 4 2 ...
 $ identity      : Ord.factor w/ 13 levels "13"<"12"<"11"<..: 11 11 13 13 11 13 13 11 13 11 ...
 $ Description   : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ GeneRatio     : chr  "11/147" "11/146" "10/211" "7/129" ...
 $ BgRatio       : chr  "176/9747" "176/9747" "176/9747" "176/9747" ...
 $ RichFactor    : num  0.0625 0.0625 0.0568 0.0398 0.2381 ...
 $ FoldEnrichment: num  4.14 4.17 2.62 3.01 74.86 ...
 $ zScore        : num  5.21 5.24 3.24 3.11 19.14 ...
 $ pvalue        : num  6.87e-05 6.45e-05 4.89e-03 8.78e-03 4.56e-09 ...
 $ p.adjust      : num  1.56e-03 2.00e-03 1.79e-02 3.88e-02 1.18e-08 ...
 $ qvalue        : num  1.03e-03 1.25e-03 8.98e-03 2.73e-02 9.59e-10 ...
 $ Count         : int  11 11 10 7 5 5 5 4 4 4 ...
 $ minuslog10padj: num  2.81 2.7 1.75 1.41 7.93 ...
 $ geneID        : chr  "6009/4602/7184/5155/3914/3674/3480/3320/1950/5525/5154" "PKN2/PPP2R3A/ANGPT1/HSP90AA1/PIK3CG/HSP90AB1/PIK3CA/LAMA2/CCND2/SOS1/RBL2" "ITGA2B/GSK3B/FGF13/ITGAV/COL6A5/ANGPT1/IL7/KIT/CREB5/HSP90B1" "6009/5154/118788/3685/5155/284/2247" ...
 $ keys          : chr  "contrast" "identity" "ID" "ID" ...
 $ DUMMY         : Ord.factor w/ 5 levels "WP_PI3KAKT_SIGNALING"<..: 1 1 1 1 4 2 5 3 2 5 ...
 - attr(*, ".internal.selfref")=<externalptr>

ORA_result_sel_max_custom_tiebreak_2
Classes ‘data.table’ and 'data.frame':	21 obs. of  17 variables:
 $ ID            : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ contrast      : Ord.factor w/ 4 levels "Genotype_rs139141690_HET_vs_wt"<..: 2 3 4 2 4 2 4 4 4 2 ...
 $ identity      : Ord.factor w/ 2 levels "1"<"3": 2 2 1 1 2 1 1 2 1 2 ...
 $ Description   : chr  "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" "WP_PI3KAKT_SIGNALING" ...
 $ GeneRatio     : chr  "11/147" "11/146" "10/211" "7/129" ...
 $ BgRatio       : chr  "176/9747" "176/9747" "176/9747" "176/9747" ...
 $ RichFactor    : num  0.0625 0.0625 0.0568 0.0398 0.2381 ...
 $ FoldEnrichment: num  4.14 4.17 2.62 3.01 74.86 ...
 $ zScore        : num  5.21 5.24 3.24 3.11 19.14 ...
 $ pvalue        : num  6.87e-05 6.45e-05 4.89e-03 8.78e-03 4.56e-09 ...
 $ p.adjust      : num  1.56e-03 2.00e-03 1.79e-02 3.88e-02 1.18e-08 ...
 $ qvalue        : num  1.03e-03 1.25e-03 8.98e-03 2.73e-02 9.59e-10 ...
 $ Count         : int  11 11 10 7 5 5 5 4 4 4 ...
 $ minuslog10padj: num  2.81 2.7 1.75 1.41 7.93 ...
 $ geneID        : chr  "6009/4602/7184/5155/3914/3674/3480/3320/1950/5525/5154" "PKN2/PPP2R3A/ANGPT1/HSP90AA1/PIK3CG/HSP90AB1/PIK3CA/LAMA2/CCND2/SOS1/RBL2" "ITGA2B/GSK3B/FGF13/ITGAV/COL6A5/ANGPT1/IL7/KIT/CREB5/HSP90B1" "6009/5154/118788/3685/5155/284/2247" ...
 $ keys          : chr  "contrast" "identity" "ID" "ID" ...
 $ DUMMY         : Ord.factor w/ 5 levels "WP_PI3KAKT_SIGNALING"<..: 1 1 1 1 4 2 5 3 2 5 ...
 - attr(*, ".internal.selfref")=<externalptr>

In [161]:
breaks_gene_sets<-as.numeric(ORA_result_sel_max_custom_tiebreak$DUMMY)
labels_gene_sets<-as.character(gsub("\\..+$","",ORA_result_sel_max_custom_tiebreak$DUMMY))

labels_gene_sets

 [1] "WP_PI3KAKT_SIGNALING"               "WP_PI3KAKT_SIGNALING"
 [3] "WP_PI3KAKT_SIGNALING"               "WP_PI3KAKT_SIGNALING"
 [5] "HP_ABNORMAL_PLATELET_VOLUME"        "AKT_UP_MTOR_DN"
 [7] "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "HP_INCREASED_MEAN_PLATELET_VOLUME"
 [9] "AKT_UP_MTOR_DN"                     "GOBP_MEGAKARYOCYTE_DIFFERENTIATION"
[11] "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "GOBP_MEGAKARYOCYTE_DIFFERENTIATION"
[13] "AKT_UP_MTOR_DN"                     "HP_ABNORMAL_PLATELET_VOLUME"
[15] "GOBP_MEGAKARYOCYTE_DIFFERENTIATION" "HP_ABNORMAL_PLATELET_VOLUME"
[17] "HP_INCREASED_MEAN_PLATELET_VOLUME"  "AKT_UP_MTOR_DN"
[19] "HP_ABNORMAL_PLATELET_VOLUME"        "HP_INCREASED_MEAN_PLATELET_VOLUME"
[21] "HP_INCREASED_MEAN_PLATELET_VOLUME"

In [165]:
ORA_lolliplot<-ggplot(data=ORA_result_sel_max_custom_tiebreak, 
                            aes(y=as.numeric(DUMMY),
                                x=minuslog10padj)) +
        geom_segment(data=ORA_result_sel_max_custom_tiebreak,
                     aes(y=as.numeric(DUMMY),
                         yend=as.numeric(DUMMY),
                         x=0,
                         xend=minuslog10padj),                     
                     size=0.8)+
        geom_point(size=5, stroke=1, shape=21, fill="white")+
        geom_text(data=ORA_result_sel_max_custom_tiebreak,
                  aes(x=minuslog10padj, y=as.numeric(DUMMY), label=Count,), size=2, family="sans",fontface="bold")+
scale_color_manual(values=c("red","blue"), drop=F)
      
      
      ORA_lolliplot <-ORA_lolliplot+
        theme_cowplot(font_size = 2,
                      font_family = "sans")+
        facet_grid(identity ~ contrast, scales='free_x', space='free_x', switch="y", drop=TRUE)+
        theme( strip.background = element_blank(),
               strip.placement = "outside",
               strip.text = element_text(size=5,color="black", family="sans"),
               panel.spacing = unit(0.2, "lines"),
               panel.background=element_rect(fill="white"),
               panel.border=element_rect(colour="white",size=0,5),
               panel.grid.major = element_blank(),
               panel.grid.minor = element_blank())+
        scale_x_continuous(name='-log10pval')+
        scale_y_continuous(name=NULL, breaks=breaks_gene_sets,
                           labels=labels_gene_sets)+
        theme_classic()+
        theme(axis.title=element_blank(),
              axis.title.y=element_blank(),
              axis.title.x=element_text(size=8,color="black", family="sans"),
              axis.text.y=element_text(size=6,color="black", family="sans", face='bold'),
              axis.text.x=element_text(size=6,color="black", family="sans"),
              axis.line.x = element_line(size = 0.4),
              axis.ticks.x = element_line(size = 0.4),
              axis.ticks.y = element_line(size = 0.4),
              axis.line.y = element_line(size = 0.4))+
        theme(legend.title = element_blank(),
              legend.text = element_text(size=6),
              legend.key.size = unit(0.5, 'cm'), #change legend key size
              legend.key.height = unit(0.5, 'cm'), #change legend key height
              legend.key.width = unit(0.5, 'cm'), #change legend key width
              legend.position="bottom")+
        guides(fill=guide_legend(nrow=1,byrow=TRUE))

In [166]:
  path_graphs = paste("/group/soranzo/manuel.tardaguila/2025_K562_multiome_reanalysis/Downstream_analysis/Figure_graphs/",sep='')
  
  if (file.exists(path_graphs)){
    
    
  }else{
    
    dir.create(file.path(path_graphs))
    
  }#path_Downstream_analysis

NULL

In [167]:
setwd(path_graphs)

svgname<-paste("Figure_5_ORA_part",".svg",sep='')

ggsave(svgname,plot=ORA_lolliplot, device ='svg', height=4, width=4)